#pragma once


// ...
#define  pKEY__DATA_PART_NAME						"DATA.PART_NAME"

#define  pKEY__DATA_PM_SIZE							"DATA.PM_SIZE"
#define  pKEY__CH_CFG_NAME_PM_X						"CH.CFG_NAME_PM%1d"

#define  pKEY__DATA_ST_SIZE							"DATA.ST_SIZE"
#define  pKEY__DATA_PRE_SUB_DIR						"DATA.PRE_SUB_DIR"
#define  pKEY__DATA_MAIN_SUB_DIR					"DATA.MAIN_SUB_DIR"
#define  pKEY__DATA_POST_SUB_DIR					"DATA.POST_SUB_DIR"

#define  pKEY__DATA_LLx_MODE						"DATA.LLx_MODE"
#define  pKEY__DATA_LLx_IN_SIZE						"DATA.LLx_IN.SIZE"
#define  pKEY__DATA_LLx_IN_ACTIVE_X					"DATA.LL%1d_IN.ACTIVE"
#define  pKEY__DATA_LLx_OUT_SIZE					"DATA.LLx_OUT.SIZE"
#define  pKEY__DATA_LLx_OUT_ACTIVE_X				"DATA.LL%1d_OUT.ACTIVE"

#define  pKEY__DATA_LOOPx_PROC_ACTIVE				"DATA.LOOPx_PROC.ACTIVE"

#define  pKEY__DATA_LLx_PROC_ACTIVE					"DATA.LLx_PROC.ACTIVE"
#define  pKEY__DATA_LLx_PROC_SIZE					"DATA.LLx_PROC.SIZE"
#define  pKEY__DATA_LLx_PROC_ACTIVE_X				"DATA.LL%1d_PROC.ACTIVE"
#define  pKEY__DATA_LL1_PROC_ACTIVE					"DATA.LL1_PROC.ACTIVE"
#define  pKEY__DATA_LL2_PROC_ACTIVE					"DATA.LL2_PROC.ACTIVE"
#define  pKEY__DATA_LL3_PROC_ACTIVE					"DATA.LL3_PROC.ACTIVE"
#define  pKEY__DATA_LL4_PROC_ACTIVE					"DATA.LL4_PROC.ACTIVE"

//
#define  pKEY__DATA_DEFAULT_AL1_CONTROL_TYPE	    "DATA.DEFAULT.AL!.CONTROL_TYPE"
#define  pKEY__DATA_DEFAULT_AL1_SLOT_TYPE           "DATA.DEFAULT.AL!.SLOT_TYPE"

#define  pKEY__DATA_DEFAULT_AL1_SLOT01_ACTIVE		"DATA.DEFAULT.AL1.SLOT01_ACTIVE"
#define  pKEY__DATA_DEFAULT_AL1_SLOT02_ACTIVE		"DATA.DEFAULT.AL1.SLOT02_ACTIVE"

//
#define  pKEY__DATA_DEFAULT_LLx_SLOT_TYPE           "DATA.DEFAULT.LLx.SLOT_TYPE"

#define  pKEY__DATA_DEFAULT_LLX_SLOT01_ACTIVE		"DATA.DEFAULT.LL%1d.SLOT01_ACTIVE"
#define  pKEY__DATA_DEFAULT_LLX_SLOT02_ACTIVE		"DATA.DEFAULT.LL%1d.SLOT02_ACTIVE"

//
#define  pKEY__DATA_LLx_OUT_COOLING_ACTIVE			"DATA.LLx_OUT.COOLING.ACTIVE"

//
#define  pKEY__DATA_STx_N2_PURGE_ACTIVE			    "DATA.STx_N2_PURGE.ACTIVE"


// ...
#define  DEF_PMx__SIZE					6

#define  _LLx_MODE__ALL					1
#define  _LLx_MODE__ONLY				2


// ...
#define  STR__YES						"YES"

#define  STR__CONFIG					"CONFIG"
#define  STR__FIXED						"FIXED"

#define  STR__ALL						"ALL"
#define  STR__ONLY_MODE					"ONLY_MODE"

#define  STR__ONLY_INPUT				"ONLY_INPUT"
#define  STR__ONLY_OUTPUT				"ONLY_OUTPUT"


