//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by JGLEE__RECIPE_CTC.rc
//
#define IDD_DLG__ROUTE_STD              4001
#define IDC_LIST__ROUTE_FILE            4001
#define IDC_BTN__CUR_ROUTE              4002
#define IDD_DLG__COMPARE_STD            4002
#define IDC_LIST__ROUTE_TABLE           4003
#define IDD_DLG__ROUTE_EDIT             4003
#define IDC_BTN__UPDATE_ROUTE           4004
#define IDC_BTN__FILE_NEW               4005
#define IDB_IMAGE_LIST                  4005
#define IDC_LIST__PMx_PRE_RCP           4006
#define IDD_DLG__PMx_RECIPE_SELECT      4006
#define IDC_BTN__FILE_UNDO              4007
#define IDD_DLG__PRC_RCP_SELECT         4007
#define IDC_BTN__FILE_SAVE              4008
#define IDC_BTN__FILE_SAVEAS            4009
#define IDC_BTN__FILE_DELETE            4010
#define IDC_BTN__ROUTE_NAME             4011
#define IDC_BTN__ROUTE_DATE             4012
#define IDC_BTN__PM1_RCP                4013
#define IDC_LIST__PMx_MAIN_RCP          4014
#define IDC_BTN__PM2_RCP                4015
#define IDB_DIGITAL_LIST_IMG            4015
#define IDC_BTN__PM3_RCP                4016
#define IDD_DLG__PMx_SELECT             4016
#define IDC_BTN__PM4_RCP                4017
#define IDD_DLG__RCP_TYPE               4017
#define IDC_BTN__PMx_PRE                4018
#define IDC_BTN__PMx_MAIN               4019
#define IDC_BTN__PMx_POST               4020
#define IDD_DLG__ROUTE_LLx              4020
#define IDC_LIST__PMx_POST_RCP          4021
#define IDD_DLG__ROUTE_ALx              4021
#define IDC_BTN__SIDE_BUFFER__TITLE     4022
#define IDC_BTN__STx__TITLE             4022
#define IDC_BTN__SEL_PMx                4023
#define IDD_DLG__ROUTE_MODE_SELECT      4023
#define IDC_BTN__ROUTE_EDIT_MODE        4024
#define IDD_DLG__ROUTE_PATH_VIEW        4024
#define IDC_BTN__ROUTE_EDIT_PATH_ID     4025
#define IDC_BTN__ROUTE_FILE_SIZE        4026
#define IDC_EDIT__MAIN_MSG              4027
#define IDD_DIALOG1                     4027
#define IDD_DLG__MDx_INFO               4027
#define IDC_EDIT__ERROR_MSG             4028
#define IDC_TREE__RESULT_REPORT         4029
#define IDC_BTN__PM5_RCP                4029
#define IDC_BTN__REF_PM_CTRL            4030
#define IDC_BTN__PM6_RCP                4030
#define IDC_TREE__ROUTE_EDIT            4031
#define IDC_BTN__REF_RECIPE_NAME        4031
#define IDC_BTN__RCP_TYPE__TITLE        4031
#define IDC_BTN__MODULE_LIST            4032
#define IDC_BTN__REF_PM_DATA            4032
#define IDC_BTN__RCP_TYPE__DATA         4032
#define IDC_BTN__ROUTE_EDIT             4033
#define IDC_BTN__REF_RCP_TYPE_CTRL      4033
#define IDC_BTN__ROUTE_FILE__LIST       4034
#define IDC_BTN__REF_RCP_TYPE_DATA      4034
#define IDC_BTN__RE_EXPAND              4035
#define IDC_BTN__ROUTE_NEW              4036
#define IDC_BTN__REF_RCP_REFRESH        4036
#define IDC_BTN__REF_RCP_UPDATE         4036
#define IDC_BTN__ROUTE_FILE__SIZE       4037
#define IDC_BTN__CHECK_RCP_UPDATE       4037
#define IDC_BTN__ROUTE_UNDO             4038
#define IDC_BTN__REF_RCP_COPY_TO_CHK_RCP 4038
#define IDC_BTN__ROUTE_SAVE             4039
#define IDC_LIST__REF_FILE              4039
#define IDC_BTN__ROUTE_SAVEAS           4040
#define IDC_TREE__PMx_RECIPE            4040
#define IDC_BTN__CHK_RCP_COPY_TO_REF_RCP 4040
#define IDC_BTN__ROUTE_EDIT__FILE_NAME  4041
#define IDC_BTN__REF_RCP_COPY_TO_OTHER_PMx 4041
#define IDC_BTN__ROUTE_EDIT__FILE_DATE  4042
#define IDC_BTN__PMC_INFO               4042
#define IDC_BTN__CHECK_PM_CTRL          4043
#define IDC_BTN__PRE_RCP_CTRL           4043
#define IDC_BTN__CUR_PMx_ID             4043
#define IDC_BTN__RE_CONTRACT            4043
#define IDC_BTN__ROUTE_FILE__DELETE     4044
#define IDC_BTN__CHECK_RECIPE_NAME      4044
#define IDC_BTN__MAIN_RCP_CTRL          4044
#define IDC_BTN__ROUTE_FILE__COPY       4045
#define IDC_BTN__CHECK_PM_DATA          4045
#define IDC_BTN__POST_RCP_CTRL          4045
#define IDC_TREE__GROUP                 4045
#define IDC_BTN__ROUTE_FILE__REFRESH    4046
#define IDC_BTN__CHECK_RCP_TYPE_CTRL    4046
#define IDC_BTN__PRE_RCP_NAME           4046
#define IDC_BTN__ROUTE_EDIT__DELETE     4047
#define IDC_BTN__CHECK_RCP_TYPE_DATA    4047
#define IDC_BTN__MAIN_RCP_NAME          4047
#define IDC_BTN__ROUTE_EDIT__PROPERTY   4048
#define IDC_BTN__CHECK_RCP_REFRESH      4048
#define IDC_BTN__POST_RCP_NAME          4048
#define IDC_BTN__ROUTE_EDIT__COPY       4049
#define IDC_LIST__CHECK_FILE            4049
#define IDC_BTN__PM1_TITLE              4050
#define IDC_BTN__RE_EXPAND_X            4050
#define IDC_BTN__REF_RCP_TYPE           4051
#define IDC_BTN__PM1_NAME               4051
#define IDC_BTN__REF_RCP_TYPE_UPDATE    4051
#define IDC_BTN__CHECK_RCP_TYPE         4052
#define IDC_BTN__PM2_TITLE              4052
#define IDC_BTN__PRE_TITLE              4052
#define IDC_BTN__CHECK_RCP_TYPE_UPDATE  4052
#define IDC_BTN__PM2_NAME               4053
#define IDC_BTN__PRE_NAME               4053
#define IDC_BTN__PM3_TITLE              4054
#define IDC_BTN__MAIN_TITLE             4054
#define IDC_BTN__REF_PM_ID_UPDATE       4054
#define IDC_BTN__PM3_NAME               4055
#define IDC_BTN__MAIN_NAME              4055
#define IDC_BTN__CHECK_PM_ID_UPDATE     4055
#define IDC_BTN__PM4_TITLE              4056
#define IDC_BTN__POST_TITLE             4056
#define IDC_EDIT__SAVE_FILE_PATH        4056
#define IDC_BTN__PM4_NAME               4057
#define IDC_BTN__POST_NAME              4057
#define IDC_CHECK__DEFUALT_ROUTE        4057
#define IDC_BTN__PM5_TITLE              4058
#define IDC_EDIT__SYS_MSG               4058
#define IDC_BTN__PM5_NAME               4059
#define IDC_BTN__PM6_TITLE              4060
#define IDC_BTN__PM6_NAME               4061
#define IDC_BTN__MODE                   4070
#define IDC_BTN__SLOT_02                4071
#define IDC_BTN__SLOT_01                4072
#define IDC_EDIT__MODE                  4073
#define IDC_EDIT__SLOT_02               4074
#define IDC_EDIT__SLOT_01               4075
#define IDC_BTN__ANGLE                  4076
#define IDC_BTN__COOLING_SEC            4076
#define IDC_EDIT__SLOT_2                4076
#define IDC_EDIT__N2_PURGE              4076
#define IDC_EDIT__ANGLE                 4077
#define IDC_EDIT__COOLING_SEC           4077
#define IDC_BTN__SLOT_MODE              4078
#define IDC_EDIT__SLOT                  4079
#define IDC_BTN__SEC                    4080
#define IDC_EDIT__INFO                  4081
#define IDC_BTN__N2_PURGE               4081
#define IDC_LIST__ITEM                  4083
#define IDC_BTN__SEL_ITEM               4084
#define IDC_TREE__ROUTE_PATH            4085
#define IDC_BTN__REPEAT                 4089
#define IDC_EDIT__REPEAT                4090
#define IDC_BTN__PMx_TITLE_1            4128
#define IDC_BTN__PMx_TITLE_2            4129
#define IDC_BTN__PMx_TITLE_3            4130
#define IDC_BTN__PMx_TITLE_4            4131
#define IDC_BTN__PMx_TITLE_5            4132
#define IDC_BTN__PMx_TITLE_6            4133
#define IDD_DLG__REPORT_MESSAGE         10121
#define IDC_LIST_TABLE                  10122
#define IDC_WIN_TITLE                   10123
#define IDC_BTN__SIDE_BUFFER__MODE      10204
#define IDC_BTN__STx_USE                10204
#define IDC_BTN__RESULT_REPORT          10205
#define IDC_BTN__PATH_VIEW              10205
#define IDC_BTN__RESULT__REF_PM         10206
#define IDC_BTN__RESULT__CHECK_PM       10210
#define IDC_BTN__RESULT_CHECK           10212
#define IDC_BTN__RESULT_SAVE            10213
#define IDC_EDIT_ACC_RATE               10214
#define IDC_BTN__RESULT__REF_RCP_NAME   10214
#define IDC_BTN__RESULT__CHECK_RCP_NAME 10215
#define IDD_DLG__ROUTE_STx              10432
#define IDC_TREE__MODULE_LIST           10433
#define IDD_DLG__ROUTE_LOOPx            10433
#define IDD_DLG__COMPARE_CFG            10434
#define IDD_DLG__PMx_SEL                10435

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4028
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         4129
#define _APS_NEXT_SYMED_VALUE           4000
#endif
#endif
