#pragma once


// ...
#define  ALID__OFFLINE_ALARM						11
#define  ALID__OFFLINE_ALARM_FULL_AUTO				12
#define  ALID__OFFLINE_ALARM_NOT_FULL_AUTO			13

// ...
#define  ALID__RF_AUTOFAIL							21
#define  ALID__RF_AUTOFAIL_FULL_AUTO				22
#define  ALID__RF_AUTOFAIL_NOT_FULL_AUTO			23

#define  ALID__RF_EXFAIL							24
#define  ALID__RF_EXFAIL_FULL_AUTO					25
#define  ALID__RF_EXFAIL_NOT_FULL_AUTO				26

#define  ALID__RF_WRITEFAIL							27
#define  ALID__RF_WRITEFAIL_FULL_AUTO				28
#define  ALID__RF_WRITEFAIL_NOT_FULL_AUTO			29

#define  ALID__RF_NOTAG								30
#define  ALID__RF_NOTAG_FULL_AUTO					31
#define  ALID__RF_NOTAG_NOT_FULL_AUTO				32

#define  ALID__RF_INVALID1							33
#define  ALID__RF_INVALID1_FULL_AUTO				34
#define  ALID__RF_INVALID1_NOT_FULL_AUTO			35

#define  ALID__RF_UNKNOWN							36
#define  ALID__RF_UNKNOWN_FULL_AUTO					37
#define  ALID__RF_UNKNOWN_NOT_FULL_AUTO				38

#define  ALID__RF_UNCONFIG							39
#define  ALID__RF_UNCONFIG_FULL_AUTO				40
#define  ALID__RF_UNCONFIG_NOT_FULL_AUTO			41

#define  ALID__RF_CHECK								42
#define  ALID__RF_CHECK_FULL_AUTO					43
#define  ALID__RF_CHECK_NOT_FULL_AUTO				44

#define  ALID__RF_VOIDACKNE							45
#define  ALID__RF_VOIDACKNE_FULL_AUTO				46
#define  ALID__RF_VOIDACKNE_NOT_FULL_AUTO			47

#define  ALID__RF_LOCKED							48
#define  ALID__RF_LOCKED_FULL_AUTO					49
#define  ALID__RF_LOCKED_NOT_FULL_AUTO				50

#define  ALID__RF_MSGLEN							51
#define  ALID__RF_MSGLEN_FULL_AUTO					52
#define  ALID__RF_MSGLEN_NOT_FULL_AUTO				53

#define  ALID__RF_INVALID2							54
#define  ALID__RF_INVALID2_FULL_AUTO				55
#define  ALID__RF_INVALID2_NOT_FULL_AUTO			56

#define  ALID__RF_NOACKN							57
#define  ALID__RF_NOACKN_FULL_AUTO					58
#define  ALID__RF_NOACKN_NOT_FULL_AUTO				59


// ...
#define  STR__ENABLE								"ENABLE"
#define  STR__YES									"YES"

